### device config ###
platformName: Android
platformVersion: 6.0.1
deviceName: ad6decf


### wuliuyun app ###
appPackage_wuliuyun: com.luchang.lcgc
appActivity_wuliuyun: .main.SplashActivity
username_wuliuyun: weibo
password_wuliuyun: 111111
partnerNo: WeiBo
# Special loan
username_specialLoan: zxcs001
password_specialLoan: 111111

### chezhu app ###
appPackage_chezhu: com.mustang
appActivity_chezhu: .account.SplashActivity

### register ###
mobile_register: 18655148783

### unregister ###
mobile_unregister: 18000001111
name_unregister: 完颜瑞星
idNo_unregister: 412725198407038239
custId_unregister: 172713
id_unregister: APP20181028171617VjVeg

### chezhu wallet consignor info ###
consignor_name: 王燕
consignor_idNo: 320621199210280523
consignor_mobile: 18020329066

### Log path ###
log_path_info: \log
log_path_error: \log\error

### DB config ###
Mysql_host: rm-uf68z8q234b903503jo.mysql.rds.aliyuncs.com
Mysql_port: 3306
Mysql_user: keking_uat
Mysql_passwd: keking@2018#hfUAT
Mysql_dbname: YDAPPDB
Mysql_charset: utf8

#########Redis Config###########
Redis_host: 101.132.155.132
Redis_port: 6379
Redis_pwd: KeKing684d
Redis_db: 1
### api-config ###
app_api_host: http://bj.uapi.yudianbank.com:8080
app_api_path: /app
app_api_YD_OAUTH: eyJlbmNyeXB0ZWREYXRhIjoiSXF1VVZqSndZYXJrL2YxL1pQZmxRT2FBYkNJWDYwOXBtQTE2SDR1K0NuR1ozWU5jcEE3anltTWphWWZEUjZkdTM1SXZGc0M0eWxCRTBKV2R1Z0Q3SzJPblFZZHJaWDdWRWFaWTR5cFJrY1hxRU1uK0dqNzJ4dTRVK1RRdjhRK3Q1QWwwdUVtcW9wTE05VThJZGkrRDBFeEdTc1RGNlQxcy80d2YxaXFMTkhDMldCV2t1MXZLcmZYeFRlV1p6VjZrK3E2eGtCU05jTDlEUGFHeXRJNnc0QXNnN2U4OGlxZVJiSndEeHc4SGtjOFZ5S3JKZFA5MDByZEd1QXdNZ2FYeXE4OXFtTENVSStiWXQ1RkU5dlI0SjAyNG1NTmxnVmNhdjB2cWVTRmRNMzdwS0VnWWFNbE9HUy9tWEhvWDF6d3Nlak5xdEpUMnZpbGw1MjNSUG4vblFnPT0iLCJ3cmFwcGVkS2V5IjoiamFTK0lISmxTVDV4VHZJT3BsRm9lOVlzVEJiR2c2SmMvdExhZXdRazYzcUV3NHZVd3djU0M3L29venMvL0p0THhVMG8xMnYwdlBjSUJTa21IemVuRkE9PSJ9

### wuliuyun_api_info ###
User-Agent: Android 6.0.1
wuliuyun_version: 3.5.15
wuliuyun_client: shipper
wuliuyun_token: eyJlbmNyeXB0ZWREYXRhIjoiNUR5WXJkRW9aclQ2S1gvMkZnTFRjeTJCSWJRUUI2T2c1MitpNnVsS09OTzhWOGR6Z2luWDFJcFg5aGY0MTVETmNJOXNiWUlJTTZTTE90YTVZZlNhdzcydTN3SklrL0x1ekwwWUtaQVVpQlNlU3dPN2VVTzlQR0R2c1VTWjN4cFNGdjZXQUI4ZEREZk5IL1pmUzNpRVg0N1JDNWlFazBxYVl3UUVvZk1wZUpjbHl2SG90emJ6b0FMQ1QwTCs3N0NNWktRYWxub2ZYSHNBWDNXQnltNnFGQktmbmxOWnV5bndIMmoyejZXbGwzTG1VWnZXZGpFbWlaOXVqSFlKTXVQTEw0SjJPVHVRY1hhLzdQT0JERTlQWHA1ZjN2Q2pSL0QxVHYzeVlNenhROHNCd2RoZzcvOXY3dXhBamZNZlZuWmJUSXpSNzVWNWhGd3ZoQkxtZktwUDlKeWorOXlMQUtWMy9wREhRdHpVZ2pQM3JtQWlobmRxWlpsWlFPNkI3QnpDaDMwNWtrRTEvT2RJTmN1Y0lkZGtESU4ySGQzdkpJMjNnbVJyOEdMZXQxOW53cEt5RWFvaGUwdGpHbnlNdm1qY2xzcUl5dkUxQkpxQzZVZjV5K1RZNThrZ2g2Z0F6Y0l0OW5jVSs5MjdPbW5Gbjc0Z0pLSjM3ZnRPUlFlUmJnL3BxZk5wYTRnNlpUYkY5elZBVEVlazBMd1NOVndqV0RhdmNiK0RtRVA4cDZmN3p6ckpMZ3o4Yy8vS0hBVXM1RVQ3cnJiY211cCtjck9IdG1kbFkrMFh3NGp5eFU0RGxiZFMyTnZvaE50eWx3MkdEa1I2U3ZGcnpKZG1ITnFwblBMTFZuYXNIZkQ3TS9RKzV5MTVJelNvOTladFVQd202cTRibUd1TkNxWHdhcWlDTmEvM1ZQVFdmbkd2RnZFUkNQOHBUWFdSbzY4L2lJazRjMXNmRys3UnErZHpBRDNMNG1PejRabmlMaWhwVG5VS1RBSkk1MzMyOXpFZ09tamFNN3B6Mm0zaEVtblAzb2RBZ0lFbFBibmhid0xzUWh2OGxCKzA1VndxTEFRRVQzUC81WVdweVNSVWd6YXZ1UnBOOE5uaVlkVVdXS3dJa2hFb2REUy9kT3psdkJzQ3RjUVU3c1N2KzkyRVh1VW44Yk9JekJCUW42eTFuK0JQUFVROURNV0ZYTS9hb255SFh5bHlMcWFDM084REVvNVBncFA3eWpsbmJkRUVvUEd6VmJFN0NJTkd4b3JFRWVpQWlObWlUSmsrOWw3WjVNdDZ6RkxsakVJVUJua2IvRVVxQVhtNHEyYTdMaDBrSUhBZFJaTGZhS0VRY2lMdGNZY0E5WFZvZUtzUDRRUlNxV3RyeUh1aTdmVDZMM2lIaEwrcFpMOWl6TGlpUUFYNUVVY24zd1NjdVcwMjROK3RZcnRJQmxSKzJtWjJTS0YwZ1Nrc1RneC9kei9iV1lLRDBYTS9tWHZmdkNXY2Vnd3h4M251Y3dxN1JzY050K2V4TDBOVk5oZlNVK3EyOE9NVm5tUDF3eFFJLzg2V2Q0bnNqSDlXa09oMkpaWTRLUTdGdlZLb2RkaENTSWlHVkUxK0J5ajdEWFZhc3cxa3Y1dk4weEVaRmh5REN2ZzFFdXR3R3RmN1ZkOHdhMVl6MWdjcjVrSStCbWFsSjdYUWIxQlJVczBKaDZCZVpvaHBaVDJWOWEzOFZTSVE1Q3RBdmZFV3h3PT0iLCJ3cmFwcGVkS2V5IjoidS9BcEErUzNqd1dyKzdDNFZua1UyY3NETmg3cForZEE3U2RNUldHUGh1Wk9JVGo5QXgvQThXQmlaOUwzeWVYYXNlN0E1aWxaS0xvRVYweUtjZzVUdGc9PSJ9
partnerNo: jUTViKluU