### device config ###
platformName: Android
platformVersion: 5.1.1
deviceName: 892ae83d

### chezhu app ###
appPackage_chezhu: com.mustang
appActivity_chezhu: .account.SplashActivity

### chezhu_api_info ###
chezhu_version: 3.13
chezhu_client: driver

### register ###
mobile_register: 18655148783
wallet_pwd_register: '123321'
driver_token_regiseter: eyJlbmNyeXB0ZWREYXRhIjoiOTVUM3FhbzhDb2l1emVBU0tZSVMwR2xCTy9Dc21jb3hOYTVXUm54VkRTRG5kYUZCS0U1Zll5d1NaNml1QVk2TFJrcUFHSVlrVXUzTkdnbFN5aTRhbDZybU9QenZwSmVObXlHK1ZvK0pTZlJRNFYrOEluVGVxbGxFSGpheG5IcGJCRkIrbC9KMXEvYzNWZ2RvWWtpSm5wcEZtSVV3RmhncTdxUGxQSkUzc1BET1BHdVVZSVhvdU5uQmZ6WVN1SmhjeUFTZzJ6cUtMTyt2WG5ZUzJMOG91UmhJSjNrUGJIWFQ2QWFSbkVaTTEyN3hPTWkwZEJLV25qK09wOTZKUE9lRCIsIndyYXBwZWRLZXkiOiJRcTkvbUZ6RjkxajFxSi9ac1NxVWZ0K3dIbTNwS0Y1RGxVZXMvVnk4S1lhWWUxL2g0MXNjdEhqWUZxZFNwbTJqNkg3UlNIZkZHR3Y4ZTBxZW1ubkVYdz09In0=

### unregister ###
mobile_unregister: 18000001111
name_unregister: 完颜瑞星
idNo_unregister: 412725198407038239
custId_unregister: 172713
id_unregister: APP20181028171617VjVeg

### chezhu wallet consignor info ###
consignor_name: 王燕
consignor_idNo: 320621199210280523
consignor_mobile: 18020329066

### Log path ###
log_path_info: \log
log_path_error: \log\error

### DB config ###
Mysql_host: rm-uf68z8q234b903503jo.mysql.rds.aliyuncs.com
Mysql_port: 3306
Mysql_user: keking_uat
Mysql_passwd: keking@2018#hfUAT
Mysql_dbname: YDAPPDB
Mysql_charset: utf8

#########Redis Config###########
Redis_host: 101.132.155.132
Redis_port: 6379
Redis_pwd: KeKing684d
Redis_db: 1

### wuliuyun_api_info ###
User-Agent: Android 6.0.1
wuliuyun_version: 3.5.15
wuliuyun_client: shipper
wuliuyun_token: eyJlbmNyeXB0ZWREYXRhIjoiL3k0Z1g4M2N1R2oxOXJBNCs2YStFcUZPZStBTHpHT1lLTXBBNUhXUUlNeWtEZDU3cWpockdUdUU1Y2FETlh0aVo4ai9uUXZWSG5EbURmZ3V0WlhjMUtrL2xQTHRBQ3QrWWFHRnB6VyswckxNQTZzQkNxMHFWUkdia1J5RjBUOGk1TmRtUzlIQzgvR2VtbElTWUxkempnclltd0hxWVJ1MndiZXVMc0l5KzFNQVVrQXI0alN6ak1lYkhBT2MyRFM4dmJ1cGk2MjhPMDFlV2xBaTA0QTg4Rk10QndTNGx2TWpGY0UwOS94UmRWY3JJbW43ck94WTNCWDByUG9SMW9vUmFmTjNYcms5L05JVXlKL1ZEcXhSUDVxV2hqRXdibmZaY0FNdEJ0bmdGeUhtck44M0YrMm1jdzhPWFFmbTNZS3AzYlplM0pSK2F6WllYc2czT3VIR3kwc1V2aWdvZ09JcTVnRUYrNmZkQ0pTanU4ZE1vQ2dHb2NRTmlaVk9Bd2sza3Zrd2lQMHp6NGlJNEpVVUlPVTJoWTBXeXZvR2tydzR2aGxCQUUrMGh3SHNaYkVwaGQ5UGFrUG1oVUttbHBXSzNTM25ZZkpoZkR6UmxBNkc5ejdWKzBodjF0bkJpNVkvQzZzWTE3ZjRQanl0UkdhVkVSaTdNUVBvbkp3eTNNRUQ4STZFZWNUSjJETTBXZGd0RUNMdGtWSzhDTzVPRTltUWFQSmZ1QTJnaWlwbmdCVllOQlpjSmNIWitVcXVBWklkTy92MjMyR3pKVFArNkc0WkNYbVNOSyt3QVp5cFV6cm5LbnM4VUZ5dnNaMTNhRTF1SmNEaVJabnRWS2xVUkxKWFFiaHhDa3o4a096eEU1dUZQS1J1L0NoWUNBQkFkNUNmaXBEc2RwTWpxcjNuOGo1ejNKbStDVmFSdzVaOWgwQWpENWZrRmQ3eWhCVTUyTHlDSS9CV3JPRE0zYXBYMDJ3bWxySGpaNUJ5M3ZCOG9YNFdzNFhZa0QzaG1hRTZid24wVWhqeTZSVk9sdk9QdDBITVJCcjUxVFFTTnVQMlNvVzJVTTdxQ3V5RmhVUzVnZGFjcDF2Y3U4WEhQNGtsT1d5L0xFb0YwNzlFY1g4RGNFQ1QwYjZKSnJ1anh3UFg0amxrWWhqV3RPbkZneFdXclZxTkFDUjVoUloxbVNpWFVWcGEvTndxNlN1R1ZyN044NStlM3JIazg3djVOSzIzNC9sTW1iQ0MxL3NaNU03WU5aUXZmK0Y2Ni9kZnBBM2FNMFFKWWJ5ZFdSMjZ4RlZKbHhKbWNoTHBGRzlNRU52S2dLTDJOMkpwQ1RDalVGVml4T2RyK0p6VUFvV2hNTnVocGxBZ1V6dm1PWGRGZUpLVkxudkozaDV4Mi9odWhBYTdtdEZ0Z1QyS04rQm11cnlyNUYwSjdrZHp2bi9JY05mcjV2THNhUjRRYWdUazhCd0dLZGF3TTZHZmc4b0dzN2xyR0FHZVNBd3c4OEhualhVWjNRS2xURzJPZ3JJbTU4SGt4akw1Snd5SFZ5TEw5dlBOOS9zQkFqYXBoTHBnZVdOYmJHVDVKZXNzdFd0SWtHV1FESm9tbjVvYjRSdXUyL3YweXB3MW9Leko1Zkp2SklBNVFEb2txZUh4aHlYbmZPdXkzQ3JMSFFTOWhISnRXRWJubDJyR1JpWDFzZ3dFRkNEMDFEQ3F2N0hXRlZveE80em1PWkZjNldGZlFpRThKZ05nRkpHVUhkeUlxSkU3R1V0ZFYwVmkwaEc2UEVsVWVIT0YyMFprIiwid3JhcHBlZEtleSI6IkxsZ2tHQVhNRGw5cGk5bFN6UmI2NXNpUE95T2pWVHozQ1VvZkZwMERwUU8vZTNkQ0pZcjF6dFRwUkNXdUFZSlpTNERUK0pJMFhKTldYUHBWLzB3SDVnPT0ifQ==
partnerNo: jUTViKluU

### wuliuyun app ###
appPackage_wuliuyun: com.luchang.lcgc
appActivity_wuliuyun: .main.SplashActivity
username_wuliuyun: 18056070690
password_wuliuyun: 111111
wuliuyun_wallet_pwd: 123321
shipper_mobile: 18056070690

### shipper card info ###
shipper_card_no: 6214835495937607
shipper_card_mobile: 18056070532
shipper_card_bank_name: '招商银行'
shipper_card_bank_branch: '测试分行'

### waybill info ###
employ_driver_mobile: 18056070690
owner_driver_mobile: 18056070690

# Special loan
username_specialLoan: zxcs001
password_specialLoan: 111111



##########Mail Config##########
#receiver eg:['eamilAddress1@keking.cn','eamilAddress2@keking.cn']
email_receiver : [ 'liuxinyu@keking.cn']
#sender
email_sender : 'ahkj@keking.cn'
email_sender_pwd : 'KeKing!@#2018'
#mail server
email_host : smtp.keking.cn
#mail title prefix
email_title : "APP-UI-BVT测试报告"